version: 2

updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: cron
      cronjob: '0 5 * * *'
      timezone: Europe/Paris
    # SvelteKit 2 et typescript-eslint 8 prennent actuellement en charge TypeScript 6 au maximum.
    ignore:
      - dependency-name: typescript
        update-types:
          - version-update:semver-major

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: cron
      cronjob: '0 5 * * *'
      timezone: Europe/Paris
